### ISSUE TITLE
Missing Semicolon Bug

### ISSUE THREAD

**Issue by NetLamp-Y** [Triploit-org/ny-5#1]
Wenn ich folgenden Code ausführen will:

```
say "Hallo Welt"
```

Kommt diese Fehlermeldung:

```
Hallo WeltException in thread "main" java.lang.IndexOutOfBoundsException: Index: 2, Size: 2
        at java.util.ArrayList.rangeCheck(Unknown Source)
        at java.util.ArrayList.get(Unknown Source)
        at com.github.triploit.npp5.run.CommandGetter.execute(CommandGetter.java:46)
        at com.github.triploit.npp5.run.Tokenizer.executeCode(Tokenizer.java:216)
        at com.github.triploit.npp5.Main.main(Main.java:127)
```

Weil das Semikolon fehlt. Soweit nicht so schlimm, höchstens etwas unschön.
Das Problem ist folgender Code:

```
say "Hallo Welt"
say "und guten Tag"
```

Hier bekomme ich als Ausgabe `Hallo Welt`, ohne eine Fehlermeldung. Ich behaupte mal, dass das nicht so sein sollte.
Würde mich freuen, wenn der Interpreter demnächst auf fehlende Semikolons hinweisen würde.
Grüße, OplGerman.

**Comment by piepert** [comment]
Ich habe den Interpreter eigentlich so geschrieben, dass er möglichst viele Fehler übersieht. Für Neueinsteiger ist das denke ich gut, kann aber natürlich auch viele Nachteile mit sich bringen.

Ich werde den Error mal anschauen und beheben. Ich werde ihn dann auch bald committen.

MfG, Survari

**Comment by piepert** [comment]
Fehler behoben.
